<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country_name' => 'Afghanistan', 'phone_code' => '93'],
            ['country_name' => 'Albania', 'phone_code' => '355'],
            ['country_name' => 'Algeria', 'phone_code' => '213'],
            ['country_name' => 'American Samoa', 'phone_code' => '1684'],
            ['country_name' => 'Andorra', 'phone_code' => '376'],
            ['country_name' => 'Angola', 'phone_code' => '244'],
            ['country_name' => 'Anguilla', 'phone_code' => '1264'],
            ['country_name' => 'Antarctica', 'phone_code' => '672'],
            ['country_name' => 'Antigua and Barbuda', 'phone_code' => '1268'],
            ['country_name' => 'Argentina', 'phone_code' => '54'],
            ['country_name' => 'Armenia', 'phone_code' => '374'],
            ['country_name' => 'Aruba', 'phone_code' => '297'],
            ['country_name' => 'Australia', 'phone_code' => '61'],
            ['country_name' => 'Austria', 'phone_code' => '43'],
            ['country_name' => 'Azerbaijan', 'phone_code' => '994'],
            ['country_name' => 'Bahamas', 'phone_code' => '1242'],
            ['country_name' => 'Bahrain', 'phone_code' => '973'],
            ['country_name' => 'Bangladesh', 'phone_code' => '880'],
            ['country_name' => 'Barbados', 'phone_code' => '1246'],
            ['country_name' => 'Belarus', 'phone_code' => '375'],
            ['country_name' => 'Belgium', 'phone_code' => '32'],
            ['country_name' => 'Belize', 'phone_code' => '501'],
            ['country_name' => 'Benin', 'phone_code' => '229'],
            ['country_name' => 'Bermuda', 'phone_code' => '1441'],
            ['country_name' => 'Bhutan', 'phone_code' => '975'],
            ['country_name' => 'Bolivia', 'phone_code' => '591'],
            ['country_name' => 'Bosnia and Herzegovina', 'phone_code' => '387'],
            ['country_name' => 'Botswana', 'phone_code' => '267'],
            ['country_name' => 'Brazil', 'phone_code' => '55'],
            ['country_name' => 'British Indian Ocean Territory', 'phone_code' => '246'],
            ['country_name' => 'British Virgin Islands', 'phone_code' => '1284'],
            ['country_name' => 'Brunei', 'phone_code' => '673'],
            ['country_name' => 'Bulgaria', 'phone_code' => '359'],
            ['country_name' => 'Burkina Faso', 'phone_code' => '226'],
            ['country_name' => 'Burundi', 'phone_code' => '257'],
            ['country_name' => 'Cambodia', 'phone_code' => '855'],
            ['country_name' => 'Cameroon', 'phone_code' => '237'],
            ['country_name' => 'Canada', 'phone_code' => '1'],
            ['country_name' => 'Cape Verde', 'phone_code' => '238'],
            ['country_name' => 'Cayman Islands', 'phone_code' => '1345'],
            ['country_name' => 'Central African Republic', 'phone_code' => '236'],
            ['country_name' => 'Chad', 'phone_code' => '235'],
            ['country_name' => 'Chile', 'phone_code' => '56'],
            ['country_name' => 'China', 'phone_code' => '86'],
            ['country_name' => 'Christmas Island', 'phone_code' => '61'],
            ['country_name' => 'Cocos Islands', 'phone_code' => '61'],
            ['country_name' => 'Colombia', 'phone_code' => '57'],
            ['country_name' => 'Comoros', 'phone_code' => '269'],
            ['country_name' => 'Cook Islands', 'phone_code' => '682'],
            ['country_name' => 'Costa Rica', 'phone_code' => '506'],
            ['country_name' => 'Croatia', 'phone_code' => '385'],
            ['country_name' => 'Cuba', 'phone_code' => '53'],
            ['country_name' => 'Curacao', 'phone_code' => '599'],
            ['country_name' => 'Cyprus', 'phone_code' => '357'],
            ['country_name' => 'Czech Republic', 'phone_code' => '420'],
            ['country_name' => 'Democratic Republic of the Congo', 'phone_code' => '243'],
            ['country_name' => 'Denmark', 'phone_code' => '45'],
            ['country_name' => 'Djibouti', 'phone_code' => '253'],
            ['country_name' => 'Dominica', 'phone_code' => '1767'],
            ['country_name' => 'Dominican Republic', 'phone_code' => '1809'],
            ['country_name' => 'Dominican Republic', 'phone_code' => '1829'],
            ['country_name' => 'Dominican Republic', 'phone_code' => '1849'],
            ['country_name' => 'East Timor', 'phone_code' => '670'],
            ['country_name' => 'Ecuador', 'phone_code' => '593'],
            ['country_name' => 'Egypt', 'phone_code' => '20'],
            ['country_name' => 'El Salvador', 'phone_code' => '503'],
            ['country_name' => 'Equatorial Guinea', 'phone_code' => '240'],
            ['country_name' => 'Eritrea', 'phone_code' => '291'],
            ['country_name' => 'Estonia', 'phone_code' => '372'],
            ['country_name' => 'Ethiopia', 'phone_code' => '251'],
            ['country_name' => 'Falkland Islands', 'phone_code' => '500'],
            ['country_name' => 'Faroe Islands', 'phone_code' => '298'],
            ['country_name' => 'Fiji', 'phone_code' => '679'],
            ['country_name' => 'Finland', 'phone_code' => '358'],
            ['country_name' => 'France', 'phone_code' => '33'],
            ['country_name' => 'French Polynesia', 'phone_code' => '689'],
            ['country_name' => 'Gabon', 'phone_code' => '241'],
            ['country_name' => 'Gambia', 'phone_code' => '220'],
            ['country_name' => 'Georgia', 'phone_code' => '995'],
            ['country_name' => 'Germany', 'phone_code' => '49'],
            ['country_name' => 'Ghana', 'phone_code' => '233'],
            ['country_name' => 'Gibraltar', 'phone_code' => '350'],
            ['country_name' => 'Greece', 'phone_code' => '30'],
            ['country_name' => 'Greenland', 'phone_code' => '299'],
            ['country_name' => 'Grenada', 'phone_code' => '1473'],
            ['country_name' => 'Guam', 'phone_code' => '1671'],
            ['country_name' => 'Guatemala', 'phone_code' => '502'],
            ['country_name' => 'Guinea', 'phone_code' => '224'],
            ['country_name' => 'Guinea-Bissau', 'phone_code' => '245'],
            ['country_name' => 'Guyana', 'phone_code' => '592'],
            ['country_name' => 'Haiti', 'phone_code' => '509'],
            ['country_name' => 'Honduras', 'phone_code' => '504'],
            ['country_name' => 'Hong Kong', 'phone_code' => '852'],
            ['country_name' => 'Hungary', 'phone_code' => '36'],
            ['country_name' => 'Iceland', 'phone_code' => '354'],
            ['country_name' => 'India', 'phone_code' => '91'],
            ['country_name' => 'Indonesia', 'phone_code' => '62'],
            ['country_name' => 'Iran', 'phone_code' => '98'],
            ['country_name' => 'Iraq', 'phone_code' => '964'],
            ['country_name' => 'Ireland', 'phone_code' => '353'],
            ['country_name' => 'Israel', 'phone_code' => '972'],
            ['country_name' => 'Italy', 'phone_code' => '39'],
            ['country_name' => 'Ivory Coast', 'phone_code' => '225'],
            ['country_name' => 'Jamaica', 'phone_code' => '1876'],
            ['country_name' => 'Japan', 'phone_code' => '81'],
            ['country_name' => 'Jordan', 'phone_code' => '962'],
            ['country_name' => 'Kazakhstan', 'phone_code' => '7'],
            ['country_name' => 'Kenya', 'phone_code' => '254'],
            ['country_name' => 'Kiribati', 'phone_code' => '686'],
            ['country_name' => 'Kosovo', 'phone_code' => '383'],
            ['country_name' => 'Kuwait', 'phone_code' => '965'],
            ['country_name' => 'Kyrgyzstan', 'phone_code' => '996'],
            ['country_name' => 'Laos', 'phone_code' => '856'],
            ['country_name' => 'Latvia', 'phone_code' => '371'],
            ['country_name' => 'Lebanon', 'phone_code' => '961'],
            ['country_name' => 'Lesotho', 'phone_code' => '266'],
            ['country_name' => 'Liberia', 'phone_code' => '231'],
            ['country_name' => 'Libya', 'phone_code' => '218'],
            ['country_name' => 'Liechtenstein', 'phone_code' => '423'],
            ['country_name' => 'Lithuania', 'phone_code' => '370'],
            ['country_name' => 'Luxembourg', 'phone_code' => '352'],
            ['country_name' => 'Macau', 'phone_code' => '853'],
            ['country_name' => 'Macedonia', 'phone_code' => '389'],
            ['country_name' => 'Madagascar', 'phone_code' => '261'],
            ['country_name' => 'Malawi', 'phone_code' => '265'],
            ['country_name' => 'Malaysia', 'phone_code' => '60'],
            ['country_name' => 'Maldives', 'phone_code' => '960'],
            ['country_name' => 'Mali', 'phone_code' => '223'],
            ['country_name' => 'Malta', 'phone_code' => '356'],
            ['country_name' => 'Marshall Islands', 'phone_code' => '692'],
            ['country_name' => 'Mauritania', 'phone_code' => '222'],
            ['country_name' => 'Mauritius', 'phone_code' => '230'],
            ['country_name' => 'Mayotte', 'phone_code' => '262'],
            ['country_name' => 'Mexico', 'phone_code' => '52'],
            ['country_name' => 'Micronesia', 'phone_code' => '691'],
            ['country_name' => 'Moldova', 'phone_code' => '373'],
            ['country_name' => 'Monaco', 'phone_code' => '377'],
            ['country_name' => 'Mongolia', 'phone_code' => '976'],
            ['country_name' => 'Montenegro', 'phone_code' => '382'],
            ['country_name' => 'Montserrat', 'phone_code' => '1664'],
            ['country_name' => 'Morocco', 'phone_code' => '212'],
            ['country_name' => 'Mozambique', 'phone_code' => '258'],
            ['country_name' => 'Myanmar', 'phone_code' => '95'],
            ['country_name' => 'Namibia', 'phone_code' => '264'],
            ['country_name' => 'Nauru', 'phone_code' => '674'],
            ['country_name' => 'Nepal', 'phone_code' => '977'],
            ['country_name' => 'Netherlands', 'phone_code' => '31'],
            ['country_name' => 'Netherlands Antilles', 'phone_code' => '599'],
            ['country_name' => 'New Caledonia', 'phone_code' => '687'],
            ['country_name' => 'New Zealand', 'phone_code' => '64'],
            ['country_name' => 'Nicaragua', 'phone_code' => '505'],
            ['country_name' => 'Niger', 'phone_code' => '227'],
            ['country_name' => 'Nigeria', 'phone_code' => '234'],
            ['country_name' => 'Niue', 'phone_code' => '683'],
            ['country_name' => 'Norfolk Island', 'phone_code' => '672'],
            ['country_name' => 'North Korea', 'phone_code' => '850'],
            ['country_name' => 'Northern Mariana Islands', 'phone_code' => '1670'],
            ['country_name' => 'Norway', 'phone_code' => '47'],
            ['country_name' => 'Oman', 'phone_code' => '968'],
            ['country_name' => 'Pakistan', 'phone_code' => '92'],
            ['country_name' => 'Palau', 'phone_code' => '680'],
            ['country_name' => 'Palestine', 'phone_code' => '970'],
            ['country_name' => 'Panama', 'phone_code' => '507'],
            ['country_name' => 'Papua New Guinea', 'phone_code' => '675'],
            ['country_name' => 'Paraguay', 'phone_code' => '595'],
            ['country_name' => 'Peru', 'phone_code' => '51'],
            ['country_name' => 'Philippines', 'phone_code' => '63'],
            ['country_name' => 'Pitcairn', 'phone_code' => '64'],
            ['country_name' => 'Poland', 'phone_code' => '48'],
            ['country_name' => 'Portugal', 'phone_code' => '351'],
            ['country_name' => 'Puerto Rico', 'phone_code' => '1787'],
            ['country_name' => 'Puerto Rico', 'phone_code' => '1939'],
            ['country_name' => 'Qatar', 'phone_code' => '974'],
            ['country_name' => 'Republic of the Congo', 'phone_code' => '242'],
            ['country_name' => 'Reunion', 'phone_code' => '262'],
            ['country_name' => 'Romania', 'phone_code' => '40'],
            ['country_name' => 'Russia', 'phone_code' => '7'],
            ['country_name' => 'Rwanda', 'phone_code' => '250'],
            ['country_name' => 'Saint Barthelemy', 'phone_code' => '590'],
            ['country_name' => 'Saint Helena', 'phone_code' => '290'],
            ['country_name' => 'Saint Kitts and Nevis', 'phone_code' => '1869'],
            ['country_name' => 'Saint Lucia', 'phone_code' => '1758'],
            ['country_name' => 'Saint Martin', 'phone_code' => '590'],
            ['country_name' => 'Saint Pierre and Miquelon', 'phone_code' => '508'],
            ['country_name' => 'Saint Vincent and the Grenadines', 'phone_code' => '1784'],
            ['country_name' => 'Samoa', 'phone_code' => '685'],
            ['country_name' => 'San Marino', 'phone_code' => '378'],
            ['country_name' => 'Sao Tome and Principe', 'phone_code' => '239'],
            ['country_name' => 'Saudi Arabia', 'phone_code' => '966'],
            ['country_name' => 'Senegal', 'phone_code' => '221'],
            ['country_name' => 'Serbia', 'phone_code' => '381'],
            ['country_name' => 'Seychelles', 'phone_code' => '248'],
            ['country_name' => 'Sierra Leone', 'phone_code' => '232'],
            ['country_name' => 'Singapore', 'phone_code' => '65'],
            ['country_name' => 'Sint Maarten', 'phone_code' => '1721'],
            ['country_name' => 'Slovakia', 'phone_code' => '421'],
            ['country_name' => 'Slovenia', 'phone_code' => '386'],
            ['country_name' => 'Solomon Islands', 'phone_code' => '677'],
            ['country_name' => 'Somalia', 'phone_code' => '252'],
            ['country_name' => 'South Africa', 'phone_code' => '27'],
            ['country_name' => 'South Korea', 'phone_code' => '82'],
            ['country_name' => 'South Sudan', 'phone_code' => '211'],
            ['country_name' => 'Spain', 'phone_code' => '34'],
            ['country_name' => 'Sri Lanka', 'phone_code' => '94'],
            ['country_name' => 'Sudan', 'phone_code' => '249'],
            ['country_name' => 'Suriname', 'phone_code' => '597'],
            ['country_name' => 'Swaziland', 'phone_code' => '268'],
            ['country_name' => 'Sweden', 'phone_code' => '46'],
            ['country_name' => 'Switzerland', 'phone_code' => '41'],
            ['country_name' => 'Syria', 'phone_code' => '963'],
            ['country_name' => 'Taiwan', 'phone_code' => '886'],
            ['country_name' => 'Tajikistan', 'phone_code' => '992'],
            ['country_name' => 'Tanzania', 'phone_code' => '255'],
            ['country_name' => 'Thailand', 'phone_code' => '66'],
            ['country_name' => 'Timor-Leste', 'phone_code' => '670'],
            ['country_name' => 'Togo', 'phone_code' => '228'],
            ['country_name' => 'Tokelau', 'phone_code' => '690'],
            ['country_name' => 'Tonga', 'phone_code' => '676'],
            ['country_name' => 'Trinidad and Tobago', 'phone_code' => '1868'],
            ['country_name' => 'Tunisia', 'phone_code' => '216'],
            ['country_name' => 'Turkey', 'phone_code' => '90'],
            ['country_name' => 'Turkmenistan', 'phone_code' => '993'],
            ['country_name' => 'Tuvalu', 'phone_code' => '688'],
            ['country_name' => 'Uganda', 'phone_code' => '256'],
            ['country_name' => 'Ukraine', 'phone_code' => '380'],
            ['country_name' => 'United Arab Emirates', 'phone_code' => '971'],
            ['country_name' => 'United Kingdom', 'phone_code' => '44'],
            ['country_name' => 'United States', 'phone_code' => '1'],
            ['country_name' => 'Uruguay', 'phone_code' => '598'],
            ['country_name' => 'Uzbekistan', 'phone_code' => '998'],
            ['country_name' => 'Vanuatu', 'phone_code' => '678'],
            ['country_name' => 'Vatican', 'phone_code' => '379'],
            ['country_name' => 'Venezuela', 'phone_code' => '58'],
            ['country_name' => 'Vietnam', 'phone_code' => '84'],
            ['country_name' => 'Wallis and Futuna', 'phone_code' => '681'],
            ['country_name' => 'Western Sahara', 'phone_code' => '212'],
            ['country_name' => 'Yemen', 'phone_code' => '967'],
            ['country_name' => 'Zambia', 'phone_code' => '260'],
            ['country_name' => 'Zimbabwe', 'phone_code' => '263']
        ];

        DB::table('countries')->insert($countries);
    }
}
